[package]
name = "bevy_pathmesh"
version = "0.3.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["pathfinding", "bevy", "navmesh"]
readme = "README.md"
description = "Navmesh plugin for Bevy"
repository = "https://github.com/vleue/bevy_pathmesh"
homepage = "https://github.com/vleue/bevy_pathmesh"
documentation = "https://docs.rs/bevy_pathmesh"
categories = ["game-development"]

[dependencies]
itertools = "0.10.5"

[dependencies.polyanya]
# version = "0.2.1"
git = "https://github.com/vleue/polyanya.git"
branch = "main"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
branch = "main"
# version = "0.9.0"
features = ["bevy_render", "bevy_asset"]
default-features = false

[dev-dependencies]
# bevy_prototype_debug_lines = "0.9"
bevy_prototype_debug_lines = { git = "https://github.com/Elabajaba/bevy_debug_lines.git", branch = "bevy_010" }
rand = "0.8"

[dev-dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
branch = "main"
# version = "0.9.0"
features = ["bevy_ui", "bevy_text", "bevy_winit", "bevy_core_pipeline", "bevy_scene", "bevy_gltf", "bevy_pbr", "bevy_sprite"]
default-features = false

[features]
default = []
linuxci = ["bevy/x11"]

[profile.dev.package."*"]
opt-level = 3
